/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiEditRouteImport } from './routes/api/ai-edit'
import { Route as ApiCodeCompletionRouteImport } from './routes/api/code-completion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiEditRoute = ApiAiEditRouteImport.update({
  id: '/api/ai-edit',
  path: '/api/ai-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodeCompletionRoute = ApiCodeCompletionRouteImport.update({
  id: '/api/code-completion',
  path: '/api/code-completion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/ai-edit': typeof ApiAiEditRoute
  '/api/code-completion': typeof ApiCodeCompletionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/ai-edit': typeof ApiAiEditRoute
  '/api/code-completion': typeof ApiCodeCompletionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/ai-edit': typeof ApiAiEditRoute
  '/api/code-completion': typeof ApiCodeCompletionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/ai-edit' | '/api/code-completion'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/ai-edit' | '/api/code-completion'
  id: '__root__' | '/' | '/api/ai-edit' | '/api/code-completion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAiEditRoute: typeof ApiAiEditRoute
  ApiCodeCompletionRoute: typeof ApiCodeCompletionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-edit': {
      id: '/api/ai-edit'
      path: '/api/ai-edit'
      fullPath: '/api/ai-edit'
      preLoaderRoute: typeof ApiAiEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-completion': {
      id: '/api/code-completion'
      path: '/api/code-completion'
      fullPath: '/api/code-completion'
      preLoaderRoute: typeof ApiCodeCompletionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAiEditRoute: ApiAiEditRoute,
  ApiCodeCompletionRoute: ApiCodeCompletionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
